package com.wynntils.modules.richpresence.discordgamesdk;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import com.wynntils.modules.richpresence.discordgamesdk.options.DiscordGameSDKOptions;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : line 250</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class DiscordImageDimensions extends Structure implements DiscordGameSDKOptions {

    public int width;
    public int height;

    public DiscordImageDimensions() {
        super();
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("width", "height");
    }

    public DiscordImageDimensions(int width, int height) {
        super();
        this.width = width;
        this.height = height;
    }

    public DiscordImageDimensions(Pointer peer) {
        super(peer);
    }

    public static class ByReference extends DiscordImageDimensions implements Structure.ByReference {

    };

    public static class ByValue extends DiscordImageDimensions implements Structure.ByValue {

    };
}
