package com.wynntils.modules.richpresence.discordgamesdk;

import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import com.sun.jna.ptr.PointerByReference;
import com.wynntils.Reference;

import java.io.File;

/**
 * JNA Wrapper for library <b>DiscordGameSDK</b><br>
 * This file was autogenerated by
 * <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that
 * <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a
 * few opensource projects.</a>.<br>
 * For help, please visit
 * <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> ,
 * <a href="http://rococoa.dev.java.net/">Rococoa</a>, or
 * <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface DiscordGameSDKLibrary extends Library {
    public static final String JNA_LIBRARY_NAME = "discord_game_sdk";
    public static final NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(new File(new File(Reference.MOD_STORAGE_ROOT, "natives"), System.mapLibraryName("discord_game_sdk")).getAbsolutePath());
    public static final DiscordGameSDKLibrary INSTANCE = (DiscordGameSDKLibrary) Native.loadLibrary(DiscordGameSDKLibrary.JNA_LIBRARY_NAME, DiscordGameSDKLibrary.class);

    /**
     * <i>native declaration : line 27</i><br>
     * enum values
     */
    public static interface EDiscordResult {
        /** <i>native declaration : line 28</i> */
        public static final int DiscordResult_Ok = 0;
        /** <i>native declaration : line 29</i> */
        public static final int DiscordResult_ServiceUnavailable = 1;
        /** <i>native declaration : line 30</i> */
        public static final int DiscordResult_InvalidVersion = 2;
        /** <i>native declaration : line 31</i> */
        public static final int DiscordResult_LockFailed = 3;
        /** <i>native declaration : line 32</i> */
        public static final int DiscordResult_InternalError = 4;
        /** <i>native declaration : line 33</i> */
        public static final int DiscordResult_InvalidPayload = 5;
        /** <i>native declaration : line 34</i> */
        public static final int DiscordResult_InvalidCommand = 6;
        /** <i>native declaration : line 35</i> */
        public static final int DiscordResult_InvalidPermissions = 7;
        /** <i>native declaration : line 36</i> */
        public static final int DiscordResult_NotFetched = 8;
        /** <i>native declaration : line 37</i> */
        public static final int DiscordResult_NotFound = 9;
        /** <i>native declaration : line 38</i> */
        public static final int DiscordResult_Conflict = 10;
        /** <i>native declaration : line 39</i> */
        public static final int DiscordResult_InvalidSecret = 11;
        /** <i>native declaration : line 40</i> */
        public static final int DiscordResult_InvalidJoinSecret = 12;
        /** <i>native declaration : line 41</i> */
        public static final int DiscordResult_NoEligibleActivity = 13;
        /** <i>native declaration : line 42</i> */
        public static final int DiscordResult_InvalidInvite = 14;
        /** <i>native declaration : line 43</i> */
        public static final int DiscordResult_NotAuthenticated = 15;
        /** <i>native declaration : line 44</i> */
        public static final int DiscordResult_InvalidAccessToken = 16;
        /** <i>native declaration : line 45</i> */
        public static final int DiscordResult_ApplicationMismatch = 17;
        /** <i>native declaration : line 46</i> */
        public static final int DiscordResult_InvalidDataUrl = 18;
        /** <i>native declaration : line 47</i> */
        public static final int DiscordResult_InvalidBase64 = 19;
        /** <i>native declaration : line 48</i> */
        public static final int DiscordResult_NotFiltered = 20;
        /** <i>native declaration : line 49</i> */
        public static final int DiscordResult_LobbyFull = 21;
        /** <i>native declaration : line 50</i> */
        public static final int DiscordResult_InvalidLobbySecret = 22;
        /** <i>native declaration : line 51</i> */
        public static final int DiscordResult_InvalidFilename = 23;
        /** <i>native declaration : line 52</i> */
        public static final int DiscordResult_InvalidFileSize = 24;
        /** <i>native declaration : line 53</i> */
        public static final int DiscordResult_InvalidEntitlement = 25;
        /** <i>native declaration : line 54</i> */
        public static final int DiscordResult_NotInstalled = 26;
        /** <i>native declaration : line 55</i> */
        public static final int DiscordResult_NotRunning = 27;
        /** <i>native declaration : line 56</i> */
        public static final int DiscordResult_InsufficientBuffer = 28;
        /** <i>native declaration : line 57</i> */
        public static final int DiscordResult_PurchaseCanceled = 29;
        /** <i>native declaration : line 58</i> */
        public static final int DiscordResult_InvalidGuild = 30;
        /** <i>native declaration : line 59</i> */
        public static final int DiscordResult_InvalidEvent = 31;
        /** <i>native declaration : line 60</i> */
        public static final int DiscordResult_InvalidChannel = 32;
        /** <i>native declaration : line 61</i> */
        public static final int DiscordResult_InvalidOrigin = 33;
        /** <i>native declaration : line 62</i> */
        public static final int DiscordResult_RateLimited = 34;
        /** <i>native declaration : line 63</i> */
        public static final int DiscordResult_OAuth2Error = 35;
        /** <i>native declaration : line 64</i> */
        public static final int DiscordResult_SelectChannelTimeout = 36;
        /** <i>native declaration : line 65</i> */
        public static final int DiscordResult_GetGuildTimeout = 37;
        /** <i>native declaration : line 66</i> */
        public static final int DiscordResult_SelectVoiceForceRequired = 38;
        /** <i>native declaration : line 67</i> */
        public static final int DiscordResult_CaptureShortcutAlreadyListening = 39;
        /** <i>native declaration : line 68</i> */
        public static final int DiscordResult_UnauthorizedForAchievement = 40;
        /** <i>native declaration : line 69</i> */
        public static final int DiscordResult_InvalidGiftCode = 41;
        /** <i>native declaration : line 70</i> */
        public static final int DiscordResult_PurchaseError = 42;
        /** <i>native declaration : line 71</i> */
        public static final int DiscordResult_TransactionAborted = 43;
    };

    /**
     * <i>native declaration : line 74</i><br>
     * enum values
     */
    public static interface EDiscordCreateFlags {
        /** <i>native declaration : line 75</i> */
        public static final int DiscordCreateFlags_Default = 0;
        /** <i>native declaration : line 76</i> */
        public static final int DiscordCreateFlags_NoRequireDiscord = 1;
    };

    /**
     * <i>native declaration : line 79</i><br>
     * enum values
     */
    public static interface EDiscordLogLevel {
        /** <i>native declaration : line 80</i> */
        public static final int DiscordLogLevel_Error = 1;
        /** <i>native declaration : line 81</i> */
        public static final int DiscordLogLevel_Warn = 2;
        /** <i>native declaration : line 82</i> */
        public static final int DiscordLogLevel_Info = 3;
        /** <i>native declaration : line 83</i> */
        public static final int DiscordLogLevel_Debug = 4;
    };

    /**
     * <i>native declaration : line 86</i><br>
     * enum values
     */
    public static interface EDiscordUserFlag {
        /** <i>native declaration : line 87</i> */
        public static final int DiscordUserFlag_Partner = 2;
        /** <i>native declaration : line 88</i> */
        public static final int DiscordUserFlag_HypeSquadEvents = 4;
        /** <i>native declaration : line 89</i> */
        public static final int DiscordUserFlag_HypeSquadHouse1 = 64;
        /** <i>native declaration : line 90</i> */
        public static final int DiscordUserFlag_HypeSquadHouse2 = 128;
        /** <i>native declaration : line 91</i> */
        public static final int DiscordUserFlag_HypeSquadHouse3 = 256;
    };

    /**
     * <i>native declaration : line 94</i><br>
     * enum values
     */
    public static interface EDiscordPremiumType {
        /** <i>native declaration : line 95</i> */
        public static final int DiscordPremiumType_None = 0;
        /** <i>native declaration : line 96</i> */
        public static final int DiscordPremiumType_Tier1 = 1;
        /** <i>native declaration : line 97</i> */
        public static final int DiscordPremiumType_Tier2 = 2;
    };

    /**
     * <i>native declaration : line 100</i><br>
     * enum values
     */
    public static interface EDiscordImageType {
        /** <i>native declaration : line 101</i> */
        public static final int DiscordImageType_User = 0;
    };

    /**
     * <i>native declaration : line 104</i><br>
     * enum values
     */
    public static interface EDiscordActivityType {
        /** <i>native declaration : line 105</i> */
        public static final int DiscordActivityType_Playing = 0;
        /** <i>native declaration : line 106</i> */
        public static final int DiscordActivityType_Streaming = 1;
        /** <i>native declaration : line 107</i> */
        public static final int DiscordActivityType_Listening = 2;
        /** <i>native declaration : line 108</i> */
        public static final int DiscordActivityType_Watching = 3;
    };

    /**
     * <i>native declaration : line 111</i><br>
     * enum values
     */
    public static interface EDiscordActivityActionType {
        /** <i>native declaration : line 112</i> */
        public static final int DiscordActivityActionType_Join = 1;
        /** <i>native declaration : line 113</i> */
        public static final int DiscordActivityActionType_Spectate = 2;
    };

    /**
     * <i>native declaration : line 116</i><br>
     * enum values
     */
    public static interface EDiscordActivityJoinRequestReply {
        /** <i>native declaration : line 117</i> */
        public static final int DiscordActivityJoinRequestReply_No = 0;
        /** <i>native declaration : line 118</i> */
        public static final int DiscordActivityJoinRequestReply_Yes = 1;
        /** <i>native declaration : line 119</i> */
        public static final int DiscordActivityJoinRequestReply_Ignore = 2;
    };

    /**
     * <i>native declaration : line 122</i><br>
     * enum values
     */
    public static interface EDiscordStatus {
        /** <i>native declaration : line 123</i> */
        public static final int DiscordStatus_Offline = 0;
        /** <i>native declaration : line 124</i> */
        public static final int DiscordStatus_Online = 1;
        /** <i>native declaration : line 125</i> */
        public static final int DiscordStatus_Idle = 2;
        /** <i>native declaration : line 126</i> */
        public static final int DiscordStatus_DoNotDisturb = 3;
    };

    /**
     * <i>native declaration : line 129</i><br>
     * enum values
     */
    public static interface EDiscordRelationshipType {
        /** <i>native declaration : line 130</i> */
        public static final int DiscordRelationshipType_None = 0;
        /** <i>native declaration : line 131</i> */
        public static final int DiscordRelationshipType_Friend = 1;
        /** <i>native declaration : line 132</i> */
        public static final int DiscordRelationshipType_Blocked = 2;
        /** <i>native declaration : line 133</i> */
        public static final int DiscordRelationshipType_PendingIncoming = 3;
        /** <i>native declaration : line 134</i> */
        public static final int DiscordRelationshipType_PendingOutgoing = 4;
        /** <i>native declaration : line 135</i> */
        public static final int DiscordRelationshipType_Implicit = 5;
    };

    /**
     * <i>native declaration : line 138</i><br>
     * enum values
     */
    public static interface EDiscordLobbyType {
        /** <i>native declaration : line 139</i> */
        public static final int DiscordLobbyType_Private = 1;
        /** <i>native declaration : line 140</i> */
        public static final int DiscordLobbyType_Public = 2;
    };

    /**
     * <i>native declaration : line 143</i><br>
     * enum values
     */
    public static interface EDiscordLobbySearchComparison {
        /** <i>native declaration : line 144</i> */
        public static final int DiscordLobbySearchComparison_LessThanOrEqual = -2;
        /** <i>native declaration : line 145</i> */
        public static final int DiscordLobbySearchComparison_LessThan = -1;
        /** <i>native declaration : line 146</i> */
        public static final int DiscordLobbySearchComparison_Equal = 0;
        /** <i>native declaration : line 147</i> */
        public static final int DiscordLobbySearchComparison_GreaterThan = 1;
        /** <i>native declaration : line 148</i> */
        public static final int DiscordLobbySearchComparison_GreaterThanOrEqual = 2;
        /** <i>native declaration : line 149</i> */
        public static final int DiscordLobbySearchComparison_NotEqual = 3;
    };

    /**
     * <i>native declaration : line 152</i><br>
     * enum values
     */
    public static interface EDiscordLobbySearchCast {
        /** <i>native declaration : line 153</i> */
        public static final int DiscordLobbySearchCast_String = 1;
        /** <i>native declaration : line 154</i> */
        public static final int DiscordLobbySearchCast_Number = 2;
    };

    /**
     * <i>native declaration : line 157</i><br>
     * enum values
     */
    public static interface EDiscordLobbySearchDistance {
        /** <i>native declaration : line 158</i> */
        public static final int DiscordLobbySearchDistance_Local = 0;
        /** <i>native declaration : line 159</i> */
        public static final int DiscordLobbySearchDistance_Default = 1;
        /** <i>native declaration : line 160</i> */
        public static final int DiscordLobbySearchDistance_Extended = 2;
        /** <i>native declaration : line 161</i> */
        public static final int DiscordLobbySearchDistance_Global = 3;
    };

    /**
     * <i>native declaration : line 164</i><br>
     * enum values
     */
    public static interface EDiscordEntitlementType {
        /** <i>native declaration : line 165</i> */
        public static final int DiscordEntitlementType_Purchase = 1;
        /** <i>native declaration : line 166</i> */
        public static final int DiscordEntitlementType_PremiumSubscription = 2;
        /** <i>native declaration : line 167</i> */
        public static final int DiscordEntitlementType_DeveloperGift = 3;
        /** <i>native declaration : line 168</i> */
        public static final int DiscordEntitlementType_TestModePurchase = 4;
        /** <i>native declaration : line 169</i> */
        public static final int DiscordEntitlementType_FreePurchase = 5;
        /** <i>native declaration : line 170</i> */
        public static final int DiscordEntitlementType_UserGift = 6;
        /** <i>native declaration : line 171</i> */
        public static final int DiscordEntitlementType_PremiumPurchase = 7;
    };

    /**
     * <i>native declaration : line 174</i><br>
     * enum values
     */
    public static interface EDiscordSkuType {
        /** <i>native declaration : line 175</i> */
        public static final int DiscordSkuType_Application = 1;
        /** <i>native declaration : line 176</i> */
        public static final int DiscordSkuType_DLC = 2;
        /** <i>native declaration : line 177</i> */
        public static final int DiscordSkuType_Consumable = 3;
        /** <i>native declaration : line 178</i> */
        public static final int DiscordSkuType_Bundle = 4;
    };

    /**
     * <i>native declaration : line 181</i><br>
     * enum values
     */
    public static interface EDiscordInputModeType {
        /** <i>native declaration : line 182</i> */
        public static final int DiscordInputModeType_VoiceActivity = 0;
        /** <i>native declaration : line 183</i> */
        public static final int DiscordInputModeType_PushToTalk = 1;
    };

    public static final int DISCORD_VERSION = (int) 2;
    public static final int DISCORD_APPLICATION_MANAGER_VERSION = (int) 1;
    public static final int DISCORD_USER_MANAGER_VERSION = (int) 1;
    public static final int DISCORD_IMAGE_MANAGER_VERSION = (int) 1;
    public static final int DISCORD_ACTIVITY_MANAGER_VERSION = (int) 1;
    public static final int DISCORD_RELATIONSHIP_MANAGER_VERSION = (int) 1;
    public static final int DISCORD_LOBBY_MANAGER_VERSION = (int) 1;
    public static final int DISCORD_NETWORK_MANAGER_VERSION = (int) 1;
    public static final int DISCORD_OVERLAY_MANAGER_VERSION = (int) 1;
    public static final int DISCORD_STORAGE_MANAGER_VERSION = (int) 1;
    public static final int DISCORD_STORE_MANAGER_VERSION = (int) 1;
    public static final int DISCORD_VOICE_MANAGER_VERSION = (int) 1;
    public static final int DISCORD_ACHIEVEMENT_MANAGER_VERSION = (int) 1;

    /**
     * Original signature :
     * <code>EDiscordResult DiscordCreate(DiscordVersion, DiscordCreateParams*, IDiscordCore**)</code><br>
     * <i>native declaration : line 639</i><br>
     * 
     * @deprecated use the safer method
     *             {@link #DiscordCreate(int, discordgamesdk.DiscordCreateParams, discordgamesdk.IDiscordCore.ByReference[])}
     *             instead
     */
    @Deprecated
    int DiscordCreate(int version, DiscordCreateParams params, PointerByReference result);

    /**
     * Original signature :
     * <code>EDiscordResult DiscordCreate(DiscordVersion, DiscordCreateParams*, IDiscordCore**)</code><br>
     * <i>native declaration : line 639</i>
     */
    int DiscordCreate(int version, DiscordCreateParams params, IDiscordCore.ByReference result[]);
}
