package com.wynntils.modules.richpresence.discordgamesdk;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import com.wynntils.modules.richpresence.discordgamesdk.enums.EDiscordStatus;
import com.wynntils.modules.richpresence.discordgamesdk.options.DiscordGameSDKOptions;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : line 296</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class DiscordPresence extends Structure implements DiscordGameSDKOptions {

    /**
     * @see EDiscordStatus<br>
     *      C type : EDiscordStatus
     */
    public EDiscordStatus status;
    /** C type : DiscordActivity */
    public DiscordActivity activity;

    public DiscordPresence() {
        super();
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("status", "activity");
    }

    /**
     * @param status   @see EDiscordStatus<br>
     *                 C type : EDiscordStatus<br>
     * @param activity C type : DiscordActivity
     */
    public DiscordPresence(EDiscordStatus status, DiscordActivity activity) {
        super();
        this.status = status;
        this.activity = activity;
    }

    public DiscordPresence(Pointer peer) {
        super(peer);
    }

    public static class ByReference extends DiscordPresence implements Structure.ByReference {

    };

    public static class ByValue extends DiscordPresence implements Structure.ByValue {

    };
}
