package com.wynntils.modules.richpresence.discordgamesdk;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import com.wynntils.modules.richpresence.discordgamesdk.enums.EDiscordEntitlementType;
import com.wynntils.modules.richpresence.discordgamesdk.options.DiscordGameSDKOptions;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : line 337</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class DiscordEntitlement extends Structure implements DiscordGameSDKOptions {

    /** C type : DiscordSnowflake */
    public long id;
    /**
     * @see EDiscordEntitlementType<br>
     *      C type : EDiscordEntitlementType
     */
    public EDiscordEntitlementType type;
    /** C type : DiscordSnowflake */
    public long sku_id;

    public DiscordEntitlement() {
        super();
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("id", "type", "sku_id");
    }

    /**
     * @param id     C type : DiscordSnowflake<br>
     * @param type   @see EDiscordEntitlementType<br>
     *               C type : EDiscordEntitlementType<br>
     * @param sku_id C type : DiscordSnowflake
     */
    public DiscordEntitlement(long id, EDiscordEntitlementType type, long sku_id) {
        super();
        this.id = id;
        this.type = type;
        this.sku_id = sku_id;
    }

    public DiscordEntitlement(Pointer peer) {
        super(peer);
    }

    public static class ByReference extends DiscordEntitlement implements Structure.ByReference {

    };

    public static class ByValue extends DiscordEntitlement implements Structure.ByValue {

    };
}
