package com.wynntils.modules.richpresence.discordgamesdk;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import com.wynntils.modules.richpresence.discordgamesdk.options.DiscordGameSDKOptions;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : line 343</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class DiscordSkuPrice extends Structure implements DiscordGameSDKOptions {

    public int amount;
    /** C type : char[16] */
    public byte[] currency = new byte[16];

    public DiscordSkuPrice() {
        super();
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("amount", "currency");
    }

    /** @param currency C type : char[16] */
    public DiscordSkuPrice(int amount, byte currency[]) {
        super();
        this.amount = amount;
        if ((currency.length != this.currency.length))
            throw new IllegalArgumentException("Wrong array size !");
        this.currency = currency;
    }

    public DiscordSkuPrice(Pointer peer) {
        super(peer);
    }

    public static class ByReference extends DiscordSkuPrice implements Structure.ByReference {

    };

    public static class ByValue extends DiscordSkuPrice implements Structure.ByValue {

    };
}
