package com.wynntils.modules.richpresence.discordgamesdk;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import com.wynntils.modules.richpresence.discordgamesdk.options.DiscordGameSDKOptions;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : line 277</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class DiscordActivitySecrets extends Structure implements DiscordGameSDKOptions {

    /** C type : char[128] */
    public byte[] match = new byte[128];
    /** C type : char[128] */
    public byte[] join = new byte[128];
    /** C type : char[128] */
    public byte[] spectate = new byte[128];

    public DiscordActivitySecrets() {
        super();
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("match", "join", "spectate");
    }

    /**
     * @param match    C type : char[128]<br>
     * @param join     C type : char[128]<br>
     * @param spectate C type : char[128]
     */
    public DiscordActivitySecrets(byte match[], byte join[], byte spectate[]) {
        super();
        if ((match.length != this.match.length))
            throw new IllegalArgumentException("Wrong array size !");
        this.match = match;
        if ((join.length != this.join.length))
            throw new IllegalArgumentException("Wrong array size !");
        this.join = join;
        if ((spectate.length != this.spectate.length))
            throw new IllegalArgumentException("Wrong array size !");
        this.spectate = spectate;
    }

    public DiscordActivitySecrets(Pointer peer) {
        super(peer);
    }

    public static class ByReference extends DiscordActivitySecrets implements Structure.ByReference {

    };

    public static class ByValue extends DiscordActivitySecrets implements Structure.ByValue {

    };
}
