package com.wynntils.modules.richpresence.discordgamesdk;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import com.wynntils.modules.richpresence.discordgamesdk.enums.EDiscordImageType;
import com.wynntils.modules.richpresence.discordgamesdk.options.DiscordGameSDKOptions;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : line 244</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class DiscordImageHandle extends Structure implements DiscordGameSDKOptions {

    /**
     * @see EDiscordImageType<br>
     *      C type : EDiscordImageType
     */
    public EDiscordImageType type;
    public long id;
    public int size;

    public DiscordImageHandle() {
        super();
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("type", "id", "size");
    }

    /**
     * @param type @see EDiscordImageType<br>
     *             C type : EDiscordImageType
     */
    public DiscordImageHandle(EDiscordImageType type, long id, int size) {
        super();
        this.type = type;
        this.id = id;
        this.size = size;
    }

    public DiscordImageHandle(Pointer peer) {
        super(peer);
    }

    public static class ByReference extends DiscordImageHandle implements Structure.ByReference {

    };

    public static class ByValue extends DiscordImageHandle implements Structure.ByValue {

    };
}
