package com.wynntils.modules.richpresence.discordgamesdk;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import com.wynntils.modules.richpresence.discordgamesdk.enums.EDiscordActivityPartyPrivacy;
import com.wynntils.modules.richpresence.discordgamesdk.options.DiscordGameSDKOptions;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : line 272</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class DiscordActivityParty extends Structure implements DiscordGameSDKOptions {

    /** C type : char[128] */
    public byte[] id = new byte[128];
    /** C type : DiscordPartySize */
    public DiscordPartySize size;
    /**
     * @see EDiscordActivityPartyPrivacy<br>
     *      C type : EDiscordActivityPartyPrivacy
     */
    public EDiscordActivityPartyPrivacy privacy;

    public DiscordActivityParty() {
        super();
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("id", "size", "privacy");
    }

    /**
     * @param id      C type : char[128]<br>
     * @param size    C type : DiscordPartySize<br>
     * @param privacy C type : EDiscordActivityPartyPrivacy
     */
    public DiscordActivityParty(byte id[], DiscordPartySize size, EDiscordActivityPartyPrivacy privacy) {
        super();
        if ((id.length != this.id.length))
            throw new IllegalArgumentException("Wrong array size !");
        this.id = id;
        this.size = size;
        this.privacy = privacy;
    }

    public DiscordActivityParty(Pointer peer) {
        super(peer);
    }

    public static class ByReference extends DiscordActivityParty implements Structure.ByReference {

    };

    public static class ByValue extends DiscordActivityParty implements Structure.ByValue {

    };
}
