package com.wynntils.modules.richpresence.discordgamesdk;

import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import com.wynntils.modules.richpresence.discordgamesdk.options.DiscordGameSDKOptions;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : line 533</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class IDiscordOverlayEvents extends Structure implements DiscordGameSDKOptions {

    /** C type : on_toggle_callback* */
    public IDiscordOverlayEvents.on_toggle_callback on_toggle;

    public interface on_toggle_callback extends Callback, DiscordGameSDKOptions {
        void apply(Pointer event_data, byte locked);
    };

    public IDiscordOverlayEvents() {
        super();
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("on_toggle");
    }

    /** @param on_toggle C type : on_toggle_callback* */
    public IDiscordOverlayEvents(IDiscordOverlayEvents.on_toggle_callback on_toggle) {
        super();
        this.on_toggle = on_toggle;
    }

    public IDiscordOverlayEvents(Pointer peer) {
        super(peer);
    }

    public static class ByReference extends IDiscordOverlayEvents implements Structure.ByReference {

    };

    public static class ByValue extends IDiscordOverlayEvents implements Structure.ByValue {

    };
}
