package com.wynntils.modules.richpresence.discordgamesdk;

import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import com.wynntils.modules.richpresence.discordgamesdk.enums.EDiscordActivityActionType;
import com.wynntils.modules.richpresence.discordgamesdk.options.DiscordGameSDKOptions;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : line 417</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class IDiscordActivityEvents extends Structure implements DiscordGameSDKOptions {

    /** C type : on_activity_join_callback* */
    public IDiscordActivityEvents.on_activity_join_callback on_activity_join;
    /** C type : on_activity_spectate_callback* */
    public IDiscordActivityEvents.on_activity_spectate_callback on_activity_spectate;
    /** C type : on_activity_join_request_callback* */
    public IDiscordActivityEvents.on_activity_join_request_callback on_activity_join_request;
    /** C type : on_activity_invite_callback* */
    public IDiscordActivityEvents.on_activity_invite_callback on_activity_invite;

    public interface on_activity_join_callback extends Callback, DiscordGameSDKOptions {
        void apply(Pointer event_data, String secret);
    };

    public interface on_activity_spectate_callback extends Callback, DiscordGameSDKOptions {
        void apply(Pointer event_data, String secret);
    };

    public interface on_activity_join_request_callback extends Callback, DiscordGameSDKOptions {
        void apply(Pointer event_data, DiscordUser user);
    };

    public interface on_activity_invite_callback extends Callback, DiscordGameSDKOptions {
        void apply(Pointer event_data, EDiscordActivityActionType type, DiscordUser user, DiscordActivity activity);
    };

    public IDiscordActivityEvents() {
        super();
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("on_activity_join", "on_activity_spectate", "on_activity_join_request", "on_activity_invite");
    }

    /**
     * @param on_activity_join         C type : on_activity_join_callback*<br>
     * @param on_activity_spectate     C type : on_activity_spectate_callback*<br>
     * @param on_activity_join_request C type : on_activity_join_request_callback*<br>
     * @param on_activity_invite       C type : on_activity_invite_callback*
     */
    public IDiscordActivityEvents(IDiscordActivityEvents.on_activity_join_callback on_activity_join, IDiscordActivityEvents.on_activity_spectate_callback on_activity_spectate, IDiscordActivityEvents.on_activity_join_request_callback on_activity_join_request, IDiscordActivityEvents.on_activity_invite_callback on_activity_invite) {
        super();
        this.on_activity_join = on_activity_join;
        this.on_activity_spectate = on_activity_spectate;
        this.on_activity_join_request = on_activity_join_request;
        this.on_activity_invite = on_activity_invite;
    }

    public IDiscordActivityEvents(Pointer peer) {
        super(peer);
    }

    public static class ByReference extends IDiscordActivityEvents implements Structure.ByReference {

    };

    public static class ByValue extends IDiscordActivityEvents implements Structure.ByValue {

    };
}
