package com.wynntils.modules.richpresence.discordgamesdk;

import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import com.wynntils.modules.richpresence.discordgamesdk.options.DiscordGameSDKOptions;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : line 575</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class IDiscordStoreEvents extends Structure implements DiscordGameSDKOptions {

    /** C type : on_entitlement_create_callback* */
    public IDiscordStoreEvents.on_entitlement_create_callback on_entitlement_create;
    /** C type : on_entitlement_delete_callback* */
    public IDiscordStoreEvents.on_entitlement_delete_callback on_entitlement_delete;

    public interface on_entitlement_create_callback extends Callback, DiscordGameSDKOptions {
        void apply(Pointer event_data, DiscordEntitlement entitlement);
    };

    public interface on_entitlement_delete_callback extends Callback, DiscordGameSDKOptions {
        void apply(Pointer event_data, DiscordEntitlement entitlement);
    };

    public IDiscordStoreEvents() {
        super();
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("on_entitlement_create", "on_entitlement_delete");
    }

    /**
     * @param on_entitlement_create C type : on_entitlement_create_callback*<br>
     * @param on_entitlement_delete C type : on_entitlement_delete_callback*
     */
    public IDiscordStoreEvents(IDiscordStoreEvents.on_entitlement_create_callback on_entitlement_create, IDiscordStoreEvents.on_entitlement_delete_callback on_entitlement_delete) {
        super();
        this.on_entitlement_create = on_entitlement_create;
        this.on_entitlement_delete = on_entitlement_delete;
    }

    public IDiscordStoreEvents(Pointer peer) {
        super(peer);
    }

    public static class ByReference extends IDiscordStoreEvents implements Structure.ByReference {

    };

    public static class ByValue extends IDiscordStoreEvents implements Structure.ByValue {

    };
}
